- src/main/kotlin/id/walt/auditor/AuditorService.kt
- src/test/kotlin/id/walt/auditor/AuditorTest.kt
- src/test/kotlin/id/walt/cli/VcVerifyCommandTest.kt
> Feat auditor cli api

- build.gradle.kts
- src/main/kotlin/id/walt/cli/VcCommand.kt
- src/main/kotlin/id/walt/cli/WaltCLI.kt
- src/main/kotlin/id/walt/services/vc/VcUtils.kt
- src/main/kotlin/id/walt/signatory/CLIDataProvider.kt
pull vc import and CLI data provider POC
> Feat vc import

- src/main/kotlin/id/walt/model/AnyDid.kt
- src/main/kotlin/id/walt/model/DecentralizedIdentifier.kt
- src/main/kotlin/id/walt/model/DidEbsi.kt
- src/main/kotlin/id/walt/services/did/DidService.kt
- src/test/kotlin/id/walt/deprecated/DidServiceTest.kt
> refactor any did, making use of abstract base class

- src/main/kotlin/id/walt/cli/EssifCommand.kt
- src/main/kotlin/id/walt/cli/WaltCLI.kt
- src/main/kotlin/id/walt/model/Ebsi.kt
- src/main/kotlin/id/walt/services/essif/TrustedIssuerClient.kt
- src/test/kotlin/id/walt/services/essif/TrustedIssuerClientTest.kt
Call to EBSI ledger to get issuer record by its DID.
> essif tir - get issuer

- src/main/kotlin/id/walt/model/DidUrl.kt
- src/test/kotlin/id/walt/services/did/DidServiceTest.kt
Changed the generateDidEbsiV2DidUrl function to be conformant with the new ebsi did specifications.
> Feat new did format

- src/main/kotlin/id/walt/services/did/DidService.kt
- src/main/resources/log4j2.xml
> Replacement of existing key-alias when importing keys

- src/main/kotlin/id/walt/model/DecentralizedIdentifier.kt
- src/main/kotlin/id/walt/model/DidEbsi.kt
- src/main/kotlin/id/walt/model/DidKey.kt
- src/main/kotlin/id/walt/services/did/DidService.kt
- src/test/kotlin/id/walt/services/did/DidServiceTest.kt
refactoring of did data model, support context as string or array
> refactor did data model and polymorphism, support context property as

- src/main/kotlin/id/walt/services/did/DidService.kt
fix didebsi serialization/deserialization
> Feat did model refactoring

- src/main/kotlin/id/walt/signatory/MergingDataProvider.kt
- src/main/kotlin/id/walt/signatory/rest/SignatoryController.kt
- src/test/kotlin/id/walt/signatory/SignatoryServiceTest.kt
> merging data provider

- s3Store.conf
- src/main/kotlin/id/walt/auditor/VerificationPolicy.kt
- src/main/kotlin/id/walt/cli/OidcCommand.kt
- src/main/kotlin/id/walt/model/dif/DisclosureLimitation.kt
- src/main/kotlin/id/walt/model/dif/InputDescriptor.kt
- src/main/kotlin/id/walt/model/dif/InputDescriptorConstraints.kt
- src/main/kotlin/id/walt/model/dif/InputDescriptorField.kt
- src/main/kotlin/id/walt/model/dif/PresentationDefinition.kt
- src/main/kotlin/id/walt/model/dif/SubmissionRequirement.kt
- src/main/kotlin/id/walt/model/dif/SubmissionRequirementRule.kt
- src/main/kotlin/id/walt/model/dif/VCFormat.kt
- src/main/kotlin/id/walt/services/oidc/OIDCUtils.kt
- src/test/kotlin/id/walt/dif/DifTest.kt
- src/test/kotlin/id/walt/services/did/DidWebTest.kt
- src/test/kotlin/id/walt/services/oidc/OIDC4VCTest.kt
- src/test/kotlin/id/walt/services/oidc/OIDCTestProvider.kt
> 120 presentation exchange 2 0

- src/main/kotlin/id/walt/auditor/Auditor.kt
- src/main/kotlin/id/walt/auditor/AuditorRestAPI.kt
- src/main/kotlin/id/walt/auditor/PolicyRegistry.kt
- src/main/kotlin/id/walt/auditor/RegoValidator.kt
- src/main/kotlin/id/walt/auditor/VerificationPolicy.kt
- src/main/kotlin/id/walt/auditor/VerificationRequest.kt
- src/main/kotlin/id/walt/auditor/dynamic/DynamicPolicy.kt
- src/main/kotlin/id/walt/auditor/dynamic/DynamicPolicyArg.kt
- src/main/kotlin/id/walt/auditor/dynamic/OPAPolicyEngine.kt
- src/main/kotlin/id/walt/auditor/dynamic/PolicyEngine.kt
- src/main/kotlin/id/walt/auditor/dynamic/PolicyEngineType.kt
- src/main/kotlin/id/walt/cli/VcCommand.kt
- src/main/kotlin/id/walt/cli/WaltCLI.kt
- src/main/kotlin/id/walt/common/CommonUtils.kt
- src/main/kotlin/id/walt/common/JsonUtils.kt
- src/main/kotlin/id/walt/rest/auditor/AuditorRestController.kt
- src/main/kotlin/id/walt/signatory/dataproviders/MergingDataProvider.kt
- src/test/kotlin/id/walt/auditor/AuditorApiTest.kt
- src/test/kotlin/id/walt/auditor/AuditorTest.kt
- src/test/kotlin/id/walt/cli/VcVerifyCommandTest.kt
- src/test/resources/verifiable-credentials/GaiaxCredential.json
- src/test/resources/verifiable-credentials/VerifiableAuthorization.json
merge opa policies into master
> 138 dynamically register opa enabled policies with the auditor

- src/main/java/com/nimbusds/oauth2/sdk/AuthorizationGrant.java
- src/main/java/com/nimbusds/oauth2/sdk/PreAuthorizedCodeGrant.java
- src/main/kotlin/id/walt/cli/OidcCommand.kt
- src/main/kotlin/id/walt/cli/WaltCLI.kt
- src/main/kotlin/id/walt/model/oidc/CredentialAuthorizationDetails.kt
- src/main/kotlin/id/walt/model/oidc/CredentialIssuer.kt
- src/main/kotlin/id/walt/model/oidc/CredentialMetadata.kt
- src/main/kotlin/id/walt/model/oidc/CredentialRequest.kt
- src/main/kotlin/id/walt/model/oidc/CredentialResponse.kt
- src/main/kotlin/id/walt/model/oidc/IssuanceInitiationRequest.kt
- src/main/kotlin/id/walt/model/oidc/JwtProof.kt
- src/main/kotlin/id/walt/model/oidc/OIDCProvider.kt
- src/main/kotlin/id/walt/model/oidc/ParsingUtils.kt
- src/main/kotlin/id/walt/services/jwt/WaltIdJwtService.kt
- src/main/kotlin/id/walt/services/oidc/OIDC4CIService.kt
- src/main/kotlin/id/walt/services/oidc/OIDC4VPService.kt
- src/test/kotlin/id/walt/services/essif/WCTTest.kt
- src/test/kotlin/id/walt/services/oidc/OIDC4VCTest.kt
- src/test/kotlin/id/walt/services/oidc/OIDCTestProvider.kt
> 172 oidc4vci spec update

- src/main/kotlin/id/walt/cli/KeyCommand.kt
- src/main/kotlin/id/walt/crypto/CryptFun.kt
- src/main/kotlin/id/walt/crypto/LdSigner.kt
- src/main/kotlin/id/walt/crypto/LdVerifier.kt
- src/main/kotlin/id/walt/services/crypto/SunCryptoService.kt
- src/main/kotlin/id/walt/services/crypto/TinkCryptoService.kt
- src/main/kotlin/id/walt/services/did/DidService.kt
- src/main/kotlin/id/walt/services/jwt/WaltIdJwtService.kt
- src/main/kotlin/id/walt/services/key/KeyService.kt
- src/main/kotlin/id/walt/services/key/WaltIdKeyService.kt
- src/main/kotlin/id/walt/services/key/import/KeyImportStrategy.kt
- src/main/kotlin/id/walt/services/keystore/TinkKeyStoreService.kt
- src/main/kotlin/id/walt/services/keystore/azure/AzureKeyStore.kt
- src/test/kotlin/id/walt/cli/DidCommandTest.kt
- src/test/kotlin/id/walt/cli/KeyCommandTest.kt
- src/test/kotlin/id/walt/services/did/DidServiceTest.kt
- src/test/kotlin/id/walt/services/key/KeyServiceTest.kt
> Feat secp256r1

- build.gradle.kts
- src/main/kotlin/id/walt/cli/DidCommand.kt
- src/main/kotlin/id/walt/cli/KeyCommand.kt
- src/main/kotlin/id/walt/cli/VcCommand.kt
- src/main/kotlin/id/walt/crypto/CryptFun.kt
- src/main/kotlin/id/walt/crypto/LdSigner.kt
- src/main/kotlin/id/walt/crypto/LdVerifier.kt
- src/main/kotlin/id/walt/model/DecentralizedIdentifier.kt
- src/main/kotlin/id/walt/services/crypto/SunCryptoService.kt
- src/main/kotlin/id/walt/services/crypto/TinkCryptoService.kt
- src/main/kotlin/id/walt/services/did/DidService.kt
- src/main/kotlin/id/walt/services/jwt/WaltIdJwtService.kt
- src/main/kotlin/id/walt/services/key/KeyService.kt
- src/main/kotlin/id/walt/services/key/WaltIdKeyService.kt
- src/main/kotlin/id/walt/services/key/import/KeyImportStrategy.kt
- src/main/kotlin/id/walt/services/keystore/TinkKeyStoreService.kt
- src/main/kotlin/id/walt/services/keystore/azure/AzureKeyStore.kt
- src/test/kotlin/id/walt/cli/DidCommandTest.kt
- src/test/kotlin/id/walt/cli/KeyCommandTest.kt
- src/test/kotlin/id/walt/services/did/DidServiceTest.kt
- src/test/kotlin/id/walt/services/key/KeyServiceTest.kt
- src/test/kotlin/id/walt/services/oidc/OIDC4VCTest.kt
> 164 jff implement didjwk

- src/main/kotlin/id/walt/services/did/DidService.kt
- src/main/kotlin/id/walt/services/jwt/WaltIdJwtService.kt
- src/test/kotlin/id/walt/services/vc/WaltIdJwtCredentialServiceTest.kt
* resolve did key on JWT verification from jwk propery of JWT header
* insert jwk header property when signing JWT credential with did ebsi v2
> 185 resolve did ebsi v2

- src/main/kotlin/id/walt/services/key/import/KeyImportStrategy.kt
- src/test/kotlin/id/walt/services/did/DidServiceTest.kt
fixed jwk import with missing alg parameter
> fix jwk import, if optional alg parameter is missing

- src/main/kotlin/id/walt/common/SerializationUtils.kt
- src/main/kotlin/id/walt/rest/custodian/CustodianController.kt
recent changes wrt generic credentials
> Feat generic credential

- src/test/kotlin/id/walt/signatory/SignatoryApiTest.kt
additional test for issueFromJson
> test for issueFromJson endpoint

- src/main/kotlin/id/walt/auditor/PolicyRegistry.kt
- src/main/kotlin/id/walt/auditor/PolicyRegistryService.kt
merge and resolve conflicts from https://github.com/walt-id/waltid-ssikit/pull/214
> Tdiesler ghi213

- .github/workflows/build.yml
- src/main/kotlin/id/walt/auditor/Auditor.kt
- src/main/kotlin/id/walt/auditor/VerificationPolicy.kt
- src/main/kotlin/id/walt/auditor/dynamic/OPAPolicyEngine.kt
- src/main/kotlin/id/walt/auditor/policies/CredentialPropertyVerificationPolicies.kt
- src/main/kotlin/id/walt/auditor/policies/EbsiVerificationPolicies.kt
- src/main/kotlin/id/walt/auditor/policies/SignaturePolicy.kt
- src/main/kotlin/id/walt/auditor/policies/VerifiablePresentationsPolicies.kt
- src/main/kotlin/id/walt/credentials/w3c/schema/NetworkntSchemaValidator.kt
- src/main/kotlin/id/walt/credentials/w3c/schema/PWallSchemaValidator.kt
- src/test/kotlin/id/walt/auditor/AuditorTest.kt
- src/test/kotlin/id/walt/services/vc/WaltIdJsonLdCredentialServiceTest.kt
- src/test/kotlin/id/walt/services/vc/WaltIdJwtCredentialServiceTest.kt
(Optional - not critical to merge)
Refactored verification policy result to implement operation result pattern
> refactor: verification-policy-result implement operation-result-pattern
